name: Newer Java versions

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  schedule:
    # Run daily on week days
    - cron:  '0 4 * * 1-5'
  workflow_dispatch:

jobs:
  java:
    name: Exercise Java version
    runs-on: ubuntu-22.04
    if: (github.repository == 'projectnessie/nessie' && github.event_name != 'pull_request') || contains(github.event.pull_request.labels.*.name, 'pr-newer-java')
    strategy:
      max-parallel: 1
      matrix:
        include:
          - java-version: 17
          - java-version: 21
    env:
      SPARK_LOCAL_IP: localhost

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Setup runner
      uses: ./.github/actions/setup-runner
      with:
        more-memory: 'true'
    - name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
      env:
        # Same as for ci.yml
        GRADLE_BUILD_ACTION_CACHE_KEY_ENVIRONMENT: java-11
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: nessie-ci
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ci
      with:
        cache-read-only: true
        java-version: ${{ matrix.java-version }}

    - name: Gradle / compile
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          spotlessCheck
          compileAll
          -x :nessie-quarkus:compileAll
          -x :nessie-quarkus-cli:compileAll
          -x :nessie-events-quarkus:compileAll
          --scan

    - name: Gradle / Compile Quarkus
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          :nessie-quarkus:compileAll
          :nessie-quarkus-cli:compileAll
          :nessie-events-quarkus:compileAll
          --scan

    - name: Gradle / unit test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test --scan

    - name: Gradle / check incl. integ-test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check --scan

    - name: Gradle / assemble + publish local
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble publishToMavenLocal --scan

    - name: Gradle / build tools integration tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildToolsIntegrationTest

    - name: Capture Test Reports
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: test-results
        path: |
          **/build/reports/*
          **/build/test-results/*
        retention-days: 7
